Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Proyecto.Models;
using Sanatorio.Models;
using System.Net;
using System.Net.Mail;
using Microsoft.EntityFrameworkCore;


namespace Proyecto.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private readonly SanatorioContext db;

        public AdminController(ILogger<AdminController> logger, SanatorioContext contexto) {
            this._logger = logger;
            this.db = contexto;
        }

        public IActionResult InicioSesionAdmin(){
            return View();
        }

        [HttpPost]
        public IActionResult LoginAdmin(string usuario, string contraseña){
            Admin adminLogin = db.Admin.FirstOrDefault(admin => admin.Usuario == usuario);
            if(adminLogin != null){
                if(adminLogin.Contraseña == contraseña){
                    AgregarAdminASession(adminLogin);
                    return View("AdminHome");
                }else{
                    ViewBag.ErrorEnLogin = true;
                    return View("InicioSesionAdmin");
                }
            }else{
                ViewBag.ErrorEnLogin = true;
                return View("InicioSesionAdmin");
            }
        }

        public IActionResult AdminHome(){
            return View();
        }

        public IActionResult VerMedicos(){
            ViewBag.Medicos = db.Medico.Include(m => m.RolEnEspecialidad).Include(m => m.Especialidad).OrderBy(m => m.Especialidad.Nombre).ToList();
            ViewBag.Especialidades = db.Especialidad.ToList();
            ViewBag.Roles = db.Rol.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult EditarMedico(int ID, string especialidad, string rolEnEspecialidad)
        {
            Medico medico = db.Medico.Include(m => m.Especialidad).Include(m => m.RolEnEspecialidad).FirstOrDefault(n => n.ID == ID);
            medico.Especialidad = db.Especialidad.FirstOrDefault(e => e.Nombre == especialidad);
            medico.RolEnEspecialidad = db.Rol.FirstOrDefault(r => r.Nombre == rolEnEspecialidad);

            db.Medico.Update(medico);
            db.SaveChanges();

            return Redirect("VerMedicos");
        }

        public IActionResult EliminarMedico(int ID)
        {
            Medico medico = db.Medico.FirstOrDefault(m => m.ID == ID);
            
            db.Medico.Remove(medico);
            db.SaveChanges();

            return Redirect("VerMedicos");
        }

        public IActionResult ResultadoDelProceso(){
            return View();
        }

        [HttpPost]
        public IActionResult AgregarMedico(string nombreYApellido, string especialidad, string rolEnEspecialidad) {
            Especialidad esp = db.Especialidad.FirstOrDefault(e => e.Nombre == especialidad);
            Rol rol = db.Rol.FirstOrDefault(r => r.Nombre == rolEnEspecialidad);
            Medico nuevoMedico = new Medico{
                NombreYApellido = nombreYApellido,
                Especialidad = esp,
                RolEnEspecialidad = rol
            };
            
            ViewBag.Boton = "Medicos";
            ViewBag.URL = "/Admin/VerMedicos";
            ViewBag.Info = " El profesional " + nombreYApellido + " con la especialidad " + especialidad + " fue agregado con exito !";
            db.Medico.Add(nuevoMedico);
            db.SaveChanges();
            return View("ResultadoDelProceso");
        }

        

        public IActionResult VerObrasSociales(){
            ViewBag.ObrasSociales = db.ObraSocial.OrderBy(o => o.Nombre).ToList();
            return View();
        }

        [HttpPost]
        public IActionResult EditarObraSocial(int ID, string nombre, string web, string estado) {
            ObraSocial obraSocial = db.ObraSocial.FirstOrDefault(os => os.ID == ID);
            obraSocial.Nombre = nombre;
            obraSocial.PaginaWeb = web;
            obraSocial.Estado = estado;

            db.ObraSocial.Update(obraSocial);
            db.SaveChanges();

            return Redirect("VerObrasSociales");
        }

        public IActionResult EliminarObraSocial(int ID) {
            ObraSocial obraSocial = db.ObraSocial.FirstOrDefault(os => os.ID == ID);
            
            db.ObraSocial.Remove(obraSocial);
            db.SaveChanges();

            return Redirect("VerObrasSociales");
        }

        public IActionResult AgregarDatos(){
            ViewBag.Especialidades = db.Especialidad.ToList();
            ViewBag.Roles = db.Rol.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult AgregarObraSocial(string nombre, string web, string estado){
            ObraSocial obraSocial = db.ObraSocial.FirstOrDefault(os => os.Nombre == nombre);
            if(obraSocial != null){
                ViewBag.Error = true;
                return View("ResultadoDelProceso");
            }
            ObraSocial nuevaOS = new ObraSocial{
                Nombre = nombre,
                PaginaWeb = web,
                Estado = estado
            };

            ViewBag.Boton = "Obras Sociales";
            ViewBag.URL = "/Admin/VerObrasSociales";
            ViewBag.Info = "La obra social " + nombre + " fue agregada con exito !" ;
            db.ObraSocial.Add(nuevaOS);
            db.SaveChanges();
            return View("ResultadoDelProceso");
        }

        public IActionResult VerNotas(){
            ViewBag.Notas = db.Nota.ToList();
            return View("VerNotas");
        }

        [HttpPost]
        public IActionResult AgregarNota(string titulo, string cuerpo, string fecha, string imagen, string URLnota){
            Nota nuevaNota = new Nota{
                Titulo = titulo,
                Cuerpo = cuerpo,
                Fecha = fecha,
                URLImagen = imagen,
                URLNotaCompleta = URLnota
            };
            ViewBag.Boton = "Notas";
            ViewBag.URL = "/Admin/VerNotas";
            ViewBag.Info = "La nota " + titulo + " fue agregada con exito !";
            db.Nota.Add(nuevaNota);
            db.SaveChanges();
            return View("ResultadoDelProceso");
        }

        [HttpPost]
        public IActionResult EditarNota(int ID, string titulo, string cuerpo, string fecha, string imagen, string URLnota){
            Nota nota = db.Nota.FirstOrDefault(n => n.ID == ID);
            nota.Titulo = titulo;
            nota.Cuerpo = cuerpo;
            nota.Fecha = fecha;
            nota.URLImagen = imagen;
            nota.URLNotaCompleta = URLnota;

            db.Nota.Update(nota);
            db.SaveChanges();

            return Redirect("VerNotas");
        }

        public IActionResult EliminarNota(int ID){
            Nota nota = db.Nota.FirstOrDefault(n => n.ID == ID);
            
            db.Nota.Remove(nota);
            db.SaveChanges();

            return Redirect("VerNotas");
        }

        private JsonResult AgregarAdminASession(Admin adminLogin) {
           HttpContext.Session.Set<Admin>("AdminLogueado", adminLogin);
            return Json(adminLogin);
        }

        public IActionResult Salir(){
            HttpContext.Session.Remove("AdminLogueado");
            return RedirectToAction("InicioSesionAdmin") ;
        }

       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InstitucionalController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Proyecto.Models;
using Sanatorio.Models;
using Microsoft.EntityFrameworkCore;

namespace Proyecto.Controllers
{
    public class InstitucionalController : Controller
    {
        private readonly ILogger<InstitucionalController> _logger;
        private readonly SanatorioContext db;

        public InstitucionalController(ILogger<InstitucionalController> logger, SanatorioContext contexto) {
            this._logger = logger;
            this.db = contexto;
        }


        public IActionResult Historia() {
            return View();
        }

         public IActionResult Staff() {
            ViewBag.Especialidades = db.Especialidad.OrderBy(e => e.Nombre).ToList();
            ViewBag.Medicos = db.Medico.Include(m => m.Especialidad).Include(m => m.RolEnEspecialidad).ToList();
            return View();
        }

         public IActionResult Autoridades() { 
            ViewBag.Autoridades = db.Autoridad.ToList();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Proyecto.Models;
using Sanatorio.Models;

namespace Proyecto.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly SanatorioContext db;

        public UserController(ILogger<UserController> logger, SanatorioContext contexto) {
            this._logger = logger;
            this.db = contexto;
        }

        public IActionResult MisTurnos(){
            Usuario user = HttpContext.Session.Get<Usuario>("UsuarioLogueado");
            List<Turno> turnos = db.Turno.Include(t => t.Medico).Where(t => t.Paciente == user.Mail).ToList();
            if(turnos.Count() != 0){
                ViewBag.Turnos = turnos;
                return View();
            }
            ViewBag.SinTurnos = true;
            return View();
        }

        public IActionResult TurnosOnline(){
            Usuario usuarioLogeado = HttpContext.Session.Get<Usuario>("UsuarioLogueado");
            ViewBag.Nombre = usuarioLogeado.Nombre;
            ViewBag.Mail = usuarioLogeado.Mail;
            return View();
        }

        public IActionResult CancelarTurno(int ID){
            Turno turno = db.Turno.FirstOrDefault(t => t.ID == ID);
            turno.Estado = "Cancelado";

            db.Turno.Update(turno);
            db.SaveChanges();
            return Redirect("MisTurnos");
        }

        public IActionResult MiPerfil(){
            Usuario usuarioLogeado = HttpContext.Session.Get<Usuario>("UsuarioLogueado");
            Usuario user = db.Usuario.FirstOrDefault(u => u.Mail == usuarioLogeado.Mail);
            ViewBag.Nombre = user.Nombre;
            ViewBag.Apellido = user.Apellido;
            ViewBag.Mail = user.Mail;
            ViewBag.ObraSocial = user.ObraSocial;
            ViewBag.Contraseña = user.Contraseña;
            ViewBag.ObrasSociales = db.ObraSocial.ToList();
            return View();
        }

        public IActionResult Transaccion(){
            return View();
        }

        public IActionResult EditarUsuario(string mail, string nombre, string apellido, string obraSocial, string contraseña){
            Usuario usuario = db.Usuario.FirstOrDefault(u => u.Mail == mail);
            usuario.ObraSocial = obraSocial;
            usuario.Contraseña = contraseña;

            db.Usuario.Update(usuario);
            db.SaveChanges();
            return View("Transaccion");
        }

        public IActionResult EliminarCuenta(string Mail){
            HttpContext.Session.Remove("UsuarioLogueado");
            Usuario usuario = db.Usuario.FirstOrDefault(u => u.Mail == Mail);
            db.Usuario.Remove(usuario);
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        
        public IActionResult Salir(){
            HttpContext.Session.Remove("UsuarioLogueado");
            return RedirectToAction("InicioSesion", "Login") ;
        }

       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/institucionalCSS.css" />
    <link rel="stylesheet" href="~/css/loggin.css" />
    <link rel="stylesheet" href="~/css/coberturasCSS.css" />
    <link rel="stylesheet" href="~/css/HomeViews.css" />
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500&display=swap" rel="stylesheet">
    <!-- FontAwesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--@RenderSection("Styles", required: false);-->
</head>

<body>
    <header>
        <div class="title-sf">
            <img src="~/Imagenes/Sanatorio-Favaloro.png">
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Institucional
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Institucional"
                                    asp-action="Historia">Nuestra Historia</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Institucional"
                                    asp-action="Staff">Staff Médico</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Institucional"
                                    asp-action="Autoridades">Autoridades</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Prestaciones">Prestaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Coberturas">Coberturas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Contacto">Contacto</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Login
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Login"
                                    asp-action="Registro">Registrate</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Login"
                                    asp-action="InicioSesion">Iniciá Sesión</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Administrador
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Admin"
                                    asp-action="InicioSesionAdmin">Iniciá Sesión</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-bottom: 2rem;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="redes-footer">
            <div>
                <span>Encontranos en las redes</span>
            </div>
            <div>
                <a href="https://www.facebook.com/Fundacion.Favaloro/" target="_blank" style="color: dimgray;"><i
                        class="fab fa-facebook"></i></a>
                <a href="https://www.instagram.com/fundacionfavaloro/" target="_blank" style="color: dimgray;"><i
                        class="fab fa-instagram"></i></a>
                <a href="https://twitter.com/fundfavaloro?lang=es" target="_blank" style="color: dimgray;"><i
                        class="fab fa-twitter"></i></a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/institucionalCSS.css" />
    <link rel="stylesheet" href="~/css/loggin.css" />
    <link rel="stylesheet" href="~/css/admin.css" />
    <link rel="stylesheet" href="~/css/HomeViews.css" />
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500&display=swap" rel="stylesheet">
    <!-- FontAwesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--@RenderSection("Styles", required: false);-->
</head>

<body>
    <header>
        <div class="title-sf">
            <img src="~/Imagenes/Sanatorio-Favaloro.png">
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="AdminHome">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                                asp-action="VerMedicos">Médicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                                asp-action="VerObrasSociales">Obras Sociales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                                asp-action="VerNotas">Notas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                                asp-action="AgregarDatos">Agregar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                                asp-action="Salir">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-bottom: 2rem;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="redes-footer">
            <div>
                <span>Administración</span>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/institucionalCSS.css" />
    <link rel="stylesheet" href="~/css/loggin.css" />
    <link rel="stylesheet" href="~/css/HomeViews.css" />
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500&display=swap" rel="stylesheet">
    <!-- FontAwesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--@RenderSection("Styles", required: false);-->
</head>

<body>
    <header>
        <div class="title-sf">
            <img src="~/Imagenes/Sanatorio-Favaloro.png">
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Institucional
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Institucional"
                                asp-action="Historia">Nuestra Historia</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Institucional"
                                asp-action="Staff">Staff Médico</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Institucional"
                                asp-action="Autoridades">Autoridades</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Prestaciones">Prestaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Coberturas">Coberturas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Contacto">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User"
                                asp-action="TurnosOnline">Turnos Online</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User"
                                asp-action="MisTurnos">Mis Turnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User"
                                asp-action="MiPerfil">Mi Perfil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User"
                                asp-action="Salir">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-bottom: 2rem;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="redes-footer">
            <div>
                <span>Encontranos en las redes</span>
            </div>
            <div>
                <a href="https://www.facebook.com/Fundacion.Favaloro/" target="_blank" style="color: dimgray;"><i
                        class="fab fa-facebook"></i></a>
                <a href="https://www.instagram.com/fundacionfavaloro/" target="_blank" style="color: dimgray;"><i
                        class="fab fa-instagram"></i></a>
                <a href="https://twitter.com/fundfavaloro?lang=es" target="_blank" style="color: dimgray;"><i
                        class="fab fa-twitter"></i></a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>